version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
  wikijs:
    build: ./build/wikijs
    volumes:
      - ./wikijs:/wikijs
      - ~/.ssh:/ssh
  proxy:
    image: nginx
    volumes:
      - ./build/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:3000"
